name: CICD

# Cuando se haga un push a main o un pull request hacia main
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # permitir ejecutar el action a mano
  workflow_dispatch:

jobs:

  build-deploy:
    # usar el runner de azure
    runs-on: [self-hosted]
    steps:
      - name: Building arco
        run: |
          cd /docker/web-dedalo
          docker build -t yuki/web-dedalo:latest -t yuki/web-dedalo:`date +%Y%m%d%H%M` .
          docker compose up -d --force-recreate


